### ISSUE TITLE
Synthesis and AlertLogPkg

### ISSUE THREAD

**Issue by rhinton** [OSVVM/OSVVM#24] opened 2017-09-12 20:36 UTC
Is there a typical approach for including alerts and logs (from AlertLogPkg) in synthesizable code?  My favorite would be to not touch the production code -- let it call AlertIf and Log all it likes -- and put the synthesis translate off/on pragmas in the package.  But that could be a significant amount of work.  

What do you think?  How are others handling this?

**Comment by JimLewis** [comment] 2017-09-12 21:01
Long term the plan is to add the pragma's to the package

**Comment by Paebbels** [comment] 2017-09-12 21:07
Hello Ryan,

I think OSVVMs logging datatypes are hard to handle in synthesis because they rely on protected types. I don't know any synthesis tool that supports PTs at elaboration time.

PoC uses `assert (not C_VERBOSE) report "any text" severity NOTE;`. 
Use cases:
1. Reporting physical settings like a UART baudrate.
2. Reporting of timing errors, caused by rounding timings or delays to whole clock cycles. Assert statements are used to log the absolute and relative timing errors in the synthesis log.
3. Checking of generic parameters and generic parameter combinations.
4. Displaying not implemented errors if a certain combination of IP cores in a wrapper IP core it not implemented yet.

More sophisticated ...  
Xilinx ISE compatible VHDL code uses file I/O operations for writing out debug code, state machine encodings, ChipScope translation files and register maps in assembler. But this is very unique to old Xilinx XST, because no other tool supports that feature :(.

**Comment by rhinton** [comment] 2017-09-12 22:37
I like the long-term plan, then.  How long is this term? :-)

To be more explicit, I have debug/simulation logging and alerts in some synthesizable code.  I don't need/want the synthesizer to *do* anything with this code, or even see it.  I'm looking for a way to keep my `Alert`s for simulation but still be able to synthesize.

It sounds like the short-term solution is to put the pragmas around my `Alert`s.  Thanks!

**Comment by rhinton** [comment] 2017-09-12 22:41
FWIW, I don't see any reason synthesis tools _couldn't_ support protected types if they chose to.  I don't see much difference between existing variables in a process, signals across multiple processes, and subprograms -- put them together, and you have a shared variable of a protected type.  Of course, I realize there is a development/testing/maintenance cost to every feature supported.  But I don't see anything inherently un-synthesizable about protected types.  (In fact, they're great for dual-port RAM behavior.)

**Comment by JimLewis** [comment] 2018-01-01 20:28
PTs should not be a problem as they will be hidden.

**Comment by JimLewis** [comment] 2020-05-09 17:36
With the additions of "synthesis translate_off" this should not be an issue.   I am closing it.   If you have issues with a specific tool, please post an issue.

**Closed by JimLewis** 2020-05-09 17:36 UTC
